require('dotenv').config()
const express = require('express')
const cors=require("cors")
const Router= require("express").Router();  
const app = express()
require('./config/Databasic')
app.use(express.json())
app.use(cors())
app.use("/api", Router)
app.listen('4000',() => console.log('Servidor Inicializado en Puerto 4000'))